// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9NJHpx_boWjpMImHKLoKS2a3swehI7Ec',
    appId: '1:314690667590:web:2a5a4fc2208af7aac4f647',
    messagingSenderId: '314690667590',
    projectId: 'dbappipt',
    authDomain: 'dbappipt.firebaseapp.com',
    storageBucket: 'dbappipt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQdCpLM85ROHo6gJld8EI2GmTilICzMrA',
    appId: '1:314690667590:android:e9fd34ef78c78986c4f647',
    messagingSenderId: '314690667590',
    projectId: 'dbappipt',
    storageBucket: 'dbappipt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMLhvtg7OCZD6yoxDz7Z2gG0yvGmpQ2gg',
    appId: '1:314690667590:ios:8dce1f3644f0ad4dc4f647',
    messagingSenderId: '314690667590',
    projectId: 'dbappipt',
    storageBucket: 'dbappipt.appspot.com',
    iosBundleId: 'com.example.aplicativoIpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMLhvtg7OCZD6yoxDz7Z2gG0yvGmpQ2gg',
    appId: '1:314690667590:ios:d68ccbec1513c409c4f647',
    messagingSenderId: '314690667590',
    projectId: 'dbappipt',
    storageBucket: 'dbappipt.appspot.com',
    iosBundleId: 'com.example.aplicativoIpt.RunnerTests',
  );
}
